### ISSUE TITLE
A cake item in 1.16

### ISSUE THREAD

**Issue by Tabinol** [PrismarineJS/prismarine-item#22]
Hello,

I am trying to obtain a cake item in Minecraft 1.16.5. What I got is a Yellow Carpet. In every list I found, 354 is for a cake.

Is it possible to help me please?

    import prismarineItem from 'prismarine-item'

    const Item = prismarineItem('1.16')

    const cake = new Item(354, 1)

  console.log(cake)

output

    Item {
      type: 354,
      count: 1,
      metadata: 0,
      nbt: null,
      name: 'yellow_carpet',
      displayName: 'Yellow Carpet',
      stackSize: 64
    }

**Comment by Karang** [comment]
354 isn't the id for a cake, use minecraft-data to know the id.

**Comment by Tabinol** [comment]
Work fine with https://github.com/PrismarineJS/node-minecraft-data/blob/HEAD/doc/api.md#minecraft-dataitemsbyname
Thank you.
