### ISSUE TITLE
Importing 'Item' class from typescript returns undefined

### ISSUE THREAD

**Issue by Camezza** [PrismarineJS/prismarine-item#30]
The Item class can be used as a type, however directly referencing the class will return undefined.
For example:

```typescript
import { Item } from 'prismarine-item';

export function logItem(item: Item) {
    console.log(`This is an item:`);
    console.log(item);
}

export function logItemClass() {
    console.log(`This is an item class:`);
    console.log(Item);
}

logItemClass();
```

Will return the following:

```
This is an item class:
undefined
```

Source code can be downloaded [here](https://www.mediafire.com/file/a2vhjplq0orgx1t/Prismarine+Item.zip/file)

**Comment by u9g** [comment]
yes, this is due to Item being a class just for typing, it's not actually there.

if you want to use Item, you can do it this way:
```ts
import * as PrisItemLoader from 'prismarine-item'
const Item = PrisItemLoader('1.12.2') // 1.12.2 is an arbitrary version
console.log(Item)
```

If you want, you can add it to typings this way.
